export const matches = [
{
    idEvent:1628388,
    strEvent:'Los Angeles Rams vs Buffalo Bills',
    strEventAlternate:'Buffalo Bills @ Los Angeles Rams',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strHomeTeam:'Los Angeles Rams',
    strAwayTeam:'Buffalo Bills',
    intHomeScore:'10',
    intRound:'1',
    intAwayScore:'31',
},
{
    idEvent:1628389,
    strEvent:'Atlanta Falcons vs New Orleans Saints',
    strEventAlternate:'New Orleans Saints @ Atlanta Falcons',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strHomeTeam:'Atlanta Falcons',
    strAwayTeam:'New Orleans Saints',
    intHomeScore:'26',
    intRound:'1',
    intAwayScore:'27',
},

{
    idEvent:1628390,
    strEvent:'Carolina Panthers vs Cleveland Browns',
    strEventAlternate:'Cleveland Browns @ Carolina Panthers',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strDescriptionEN:'',
    strHomeTeam:'Carolina Panthers',
    strAwayTeam:'Cleveland Browns',
    intHomeScore:'24',
    intRound:'1',
    intAwayScore:'26',
},

{
    idEvent:1628391,
    strEvent:'Chicago Bears vs San Francisco 49ers',
    strEventAlternate:'San Francisco 49ers @ Chicago Bears',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strDescriptionEN:'',
    strHomeTeam:'Chicago Bears',
    strAwayTeam:'San Francisco 49ers',
    intHomeScore:'19',
    intRound:'1',
    intAwayScore:'10',
},

{
    idEvent:1628392,
    strEvent:'Cincinnati Bengals vs Pittsburgh Steelers',
    strEventAlternate:'Pittsburgh Steelers @ Cincinnati Bengals',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strDescriptionEN:'',
    strHomeTeam:'Cincinnati Bengals',
    strAwayTeam:'Pittsburgh Steelers',
    intHomeScore:'20',
    intRound:'1',
    intAwayScore:'23',
},

{
    idEvent:1628393,
    strEvent:'Detroit Lions vs Philadelphia Eagles',
    strEventAlternate:'Philadelphia Eagles @ Detroit Lions',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strDescriptionEN:'',
    strHomeTeam:'Detroit Lions',
    strAwayTeam:'Philadelphia Eagles',
    intHomeScore:'35',
    intRound:'1',
    intAwayScore:'38',
},

{
    idEvent:1628394,
    strEvent:'Houston Texans vs Indianapolis Colts',
    strEventAlternate:'Indianapolis Colts @ Houston Texans',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strDescriptionEN:'',
    strHomeTeam:'Houston Texans',
    strAwayTeam:'Indianapolis Colts',
    intHomeScore:'20',
    intRound:'1',
    intAwayScore:'20',
},

{
    idEvent:1628395,
    strEvent:'Miami Dolphins vs New England Patriots',
    strEventAlternate:'New England Patriots @ Miami Dolphins',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strDescriptionEN:'The Mike McDaniel era gets underway at Hard Rock Stadium, where Bill Belichick’s New England Patriots are the visitors. The Pats have won just one of their last five games against the Miami Dolphins, who now have Tyreek Hill at their disposal.',
    strHomeTeam:'Miami Dolphins',
    strAwayTeam:'New England Patriots',
    intHomeScore:'20',
    intRound:'1',
    intAwayScore:'7',
},

{
    idEvent:1628396,
    strEvent:'New York Jets vs Baltimore Ravens',
    strEventAlternate:'Baltimore Ravens @ New York Jets',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strDescriptionEN:'',
    strHomeTeam:'New York Jets',
    strAwayTeam:'Baltimore Ravens',
    intHomeScore:'9',
    intRound:'1',
    intAwayScore:'24',
},

{
    idEvent:1628397,
    strEvent:'Washington Commanders vs Jacksonville Jaguars',
    strEventAlternate:'Jacksonville Jaguars @ Washington Commanders',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strDescriptionEN:'',
    strHomeTeam:'Washington Commanders',
    strAwayTeam:'Jacksonville Jaguars',
    intHomeScore:'28',
    intRound:'1',
    intAwayScore:'22',
},

{
    idEvent:1628398,
    strEvent:'Arizona Cardinals vs Kansas City Chiefs',
    strEventAlternate:'Kansas City Chiefs @ Arizona Cardinals',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strDescriptionEN:'',
    strHomeTeam:'Arizona Cardinals',
    strAwayTeam:'Kansas City Chiefs',
    intHomeScore:'21',
    intRound:'1',
    intAwayScore:'44',
},

{
    idEvent:1628399,
    strEvent:'Los Angeles Chargers vs Las Vegas Raiders',
    strEventAlternate:'Las Vegas Raiders @ Los Angeles Chargers',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strDescriptionEN:'The Las Vegas Raiders travel to SoFi Stadium, where a sensational NFL tie with the Los Angeles Chargers awaits. With both sides hoping to taste success in the first match week, which team will kick off the new campaign with an emphatic victory?',
    strHomeTeam:'Los Angeles Chargers',
    strAwayTeam:'Las Vegas Raiders',
    intHomeScore:'24',
    intRound:'1',
    intAwayScore:'19',
},

{
    idEvent:1628400,
    strEvent:'Minnesota Vikings vs Green Bay Packers',
    strEventAlternate:'Green Bay Packers @ Minnesota Vikings',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strDescriptionEN:'',
    strHomeTeam:'Minnesota Vikings',
    strAwayTeam:'Green Bay Packers',
    intHomeScore:'23',
    intRound:'1',
    intAwayScore:'7',
},

{
    idEvent:1628401,
    strEvent:'Tennessee Titans vs New York Giants',
    strEventAlternate:'New York Giants @ Tennessee Titans',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strDescriptionEN:'',
    strHomeTeam:'Tennessee Titans',
    strAwayTeam:'New York Giants',
    intHomeScore:'20',
    intRound:'1',
    intAwayScore:'21',
},

{
    idEvent:1628402,
    strEvent:'Dallas Cowboys vs Tampa Bay Buccaneers',
    strEventAlternate:'Tampa Bay Buccaneers @ Dallas Cowboys',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strDescriptionEN:'Enjoy a titanic opening week matchup in the NFL, as the Dallas Cowboys host the Tampa Bay Buccaneers at AT&T Stadium. With the Cowboys having won 15 of the 20 meetings between the two, can Tom Brady and the Buccaneers close the gap on match week one?',
    strHomeTeam:'Dallas Cowboys',
    strAwayTeam:'Tampa Bay Buccaneers',
    intHomeScore:'3',
    intRound:'1',
    intAwayScore:'19',
},

{
    idEvent:1628403,
    strEvent:'Seattle Seahawks vs Denver Broncos',
    strEventAlternate:'Denver Broncos @ Seattle Seahawks',
    idLeague:'4391',
    strLeague:'NFL',
    strSeason:'2022',
    strDescriptionEN:'',
    strHomeTeam:'Seattle Seahawks',
    strAwayTeam:'Denver Broncos',
    intHomeScore:'17',
    intRound:'1',
    intAwayScore:'16',
}
];
